apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: servicemeshoperator
  namespace: istio-policies
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/standards: Istio Service Mesh
    policy.open-cluster-management.io/controls: Operator Management
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: servicemeshoperator
        spec:
          remediationAction: enforce
          severity: high
          operatorGroup:
            name: global-operators
            namespace: openshift-operators
          subscription:
            name: servicemeshoperator3
            namespace: openshift-operators
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
          complianceType: musthave
          removalBehavior:
            operatorGroups: DeleteIfUnused
            customResourceDefinitions: Keep
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: mesh-clusters-servicemeshoperator
  namespace: istio-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: mesh-clusters
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: servicemeshoperator
