apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: managed-service-account
  namespace: istio-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-2 Account Management
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: managed-service-account
        spec:
          severity: high
          object-templates-raw: |
            {{- range $cluster := (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").items }}
            {{- if and (hasKey $cluster.metadata.labels "mesh") (eq (index $cluster.metadata.labels "mesh") "enabled") }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: authentication.open-cluster-management.io/v1beta1
                kind: ManagedServiceAccount
                metadata:
                  name: istio-reader-service-account
                  namespace: {{ $cluster.metadata.name }}
                spec:
                  rotation:
                    enabled: true
                    validity: 24h
            {{- else }}
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: authentication.open-cluster-management.io/v1beta1
                kind: ManagedServiceAccount
                metadata:
                  name: istio-reader-service-account
                  namespace: {{ $cluster.metadata.name }}
            {{- end }}
            {{- end }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: local-cluster
  namespace: istio-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: local-cluster
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: local-cluster-managed-service-account
  namespace: istio-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: local-cluster
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: managed-service-account
