apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: istio-reader-clusterrolebinding
  namespace: istio-policies
  annotations:
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/standards: Istio Service Mesh
    policy.open-cluster-management.io/controls: RBAC Management
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: istio-reader-clusterrolebinding
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: MustHave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: istio-reader-clusterrole-istio-system-acm
                  labels:
                    app: istio-reader
                    app.kubernetes.io/name: istio-reader
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: istio-reader-clusterrole-istio-system
                subjects:
                  - kind: ServiceAccount
                    name: istio-reader-service-account
                    namespace: open-cluster-management-agent-addon
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: mesh-clusters-istio-reader-clusterrolebinding
  namespace: istio-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: mesh-clusters
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: istio-reader-clusterrolebinding
