apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: mesh-clusters-v1
  namespace: istio-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            mesh-version: v1
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: mesh-clusters-v2
  namespace: istio-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            mesh-version: v2
