apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: sample-policies
spec:
  clusterSet: default
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: mesh-clusters
  namespace: sample-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            mesh: enabled
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: mesh-clusters-v1
  namespace: sample-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            app-version: v1
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: mesh-clusters-v2
  namespace: sample-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            app-version: v2
