apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helloworld-v1
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: mesh-clusters-v1
        requeueAfterSeconds: 180
  template:
    metadata:
      name: helloworld
    spec:
      project: default
      source:
        repoURL: https://github.com/jewertow/upstream-istio.git
        targetRevision: helloworld-samples
        path: samples/helloworld
        directory:
          include: '{helloworld-v1.yaml,helloworld-svc.yaml}'
      destination:
        namespace: sample
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            istio-injection: enabled
