apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: ca-certificate
  namespace: global-mesh-policies
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/standards: Istio Service Mesh
    policy.open-cluster-management.io/controls: Certificate Management
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ca-certificate
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: MustHave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: cacerts
                  namespace: istio-system
                type: kubernetes.io/tls
                data:
                  tls.crt: '{{hub fromSecret "global-mesh-policies" "cacerts" "tls.crt" hub}}'
                  tls.key: '{{hub fromSecret "global-mesh-policies" "cacerts" "tls.key" hub}}'
                  ca.crt: '{{hub fromSecret "global-mesh-policies" "cacerts" "ca.crt" hub}}'
