apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: control-plane
  namespace: global-mesh-policies
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/standards: Istio Service Mesh
    policy.open-cluster-management.io/controls: Istio Installation
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: control-plane
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: MustHave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: istio-system
                  labels:
                    topology.istio.io/network: 'network-{{hub .ManagedClusterName hub}}'
            - complianceType: MustHave
              objectDefinition:
                apiVersion: sailoperator.io/v1
                kind: Istio
                metadata:
                  name: default
                spec:
                  version: v1.30-latest
                  namespace: istio-system
                  updateStrategy:
                    type: InPlace
                  values:
                    meshConfig:
                      accessLogFile: /dev/stdout
                    global:
                      multiCluster:
                        clusterName: 'cluster-{{hub .ManagedClusterName hub}}'
                      network: 'network-{{hub .ManagedClusterName hub}}'
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: control-plane-reader-clusterrolebinding
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: MustHave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: istio-reader-clusterrole-istio-system-acm
                  labels:
                    app: istio-reader
                    app.kubernetes.io/name: istio-reader
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: istio-reader-clusterrole-istio-system
                subjects:
                  - kind: ServiceAccount
                    name: istio-reader-service-account
                    namespace: open-cluster-management-agent-addon
